// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXsHVexkZAtEuoemFxHvcqr-cvxlZJ4ZU',
    appId: '1:680622403947:web:1b0e4fb55c98de72c1dc2e',
    messagingSenderId: '680622403947',
    projectId: 'todyapp-a70d6',
    authDomain: 'todyapp-a70d6.firebaseapp.com',
    storageBucket: 'todyapp-a70d6.firebasestorage.app',
    measurementId: 'G-ZZG2XESF2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYLX3U4eP7sYIWO1OLF48fKtZhrusJiBY',
    appId: '1:680622403947:android:7c965e170138cd6fc1dc2e',
    messagingSenderId: '680622403947',
    projectId: 'todyapp-a70d6',
    storageBucket: 'todyapp-a70d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbB3R-TscRp6AqIll_BQNku8QshFe5GeM',
    appId: '1:680622403947:ios:0e91adf325638815c1dc2e',
    messagingSenderId: '680622403947',
    projectId: 'todyapp-a70d6',
    storageBucket: 'todyapp-a70d6.firebasestorage.app',
    iosBundleId: 'com.example.todyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbB3R-TscRp6AqIll_BQNku8QshFe5GeM',
    appId: '1:680622403947:ios:0e91adf325638815c1dc2e',
    messagingSenderId: '680622403947',
    projectId: 'todyapp-a70d6',
    storageBucket: 'todyapp-a70d6.firebasestorage.app',
    iosBundleId: 'com.example.todyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXsHVexkZAtEuoemFxHvcqr-cvxlZJ4ZU',
    appId: '1:680622403947:web:6f37d3d6262128aec1dc2e',
    messagingSenderId: '680622403947',
    projectId: 'todyapp-a70d6',
    authDomain: 'todyapp-a70d6.firebaseapp.com',
    storageBucket: 'todyapp-a70d6.firebasestorage.app',
    measurementId: 'G-VVN9MQX738',
  );
}
